### ISSUE TITLE
How was Wi-Fi screen flicker solved?

### ISSUE THREAD

**Issue by GranPC** [Shotz5/Razer-Blade-Hackintosh#2]
Hi @Shotz5, sorry for the hassle. I was wondering about this bullet point in your README:

- Airportitlwm.kext - When WiFi is in use (actively transmitting up/down) gives massive screen flickering relative to download or upload speed. Issue was actually related to WhateverGreen.kext, and has been patched with extra DeviceProperty settings in config.plist.

I have a Razer Blade 17 and I've been seeing this issue on and off for a long time, particularly on 5GHz networks. Switching from 240Hz to 60Hz immediately stops the flickering; so I just assumed it was some sort of interference with the clock signal and impossible to fix.

I tried looking through the config plist but I'm not sure which property fixed the issue. Would you happen to still remember?

Thanks!

**Comment by Shotz5** [comment]
Hi, @GranPC

Apologies, I have not even thought about this repo in a while. I don't exactly remember which configuration values fixed it but I know it was a combination of a couple. I believe including a boot value or two. I will take a look and try to remember, and get back to you.

**Comment by Shotz5** [comment]
Hi @GranPC, sorry for the obnoxiously late response. I've been busy with other stuff.

The fix was a combination of these Device Properties, I'm not *exactly* sure which ones solved the issue, but you can experiement with a combination of them to find the solution. My hunch is the FrameBuffer properties.

![image](https://i.imgur.com/VyCP4m0.png)

Hope this helps.
